### PR TITLE
Chan/landing

### PR DESCRIPTION
**Pull request by chevrechou**

### CODE REVIEW

**Comment by amanzanero** [comment]
So something with Next js is that everything under "/pages" gets served as a route by next. So I would move all the code from Landing.js and put it in /pages/index.js. Because right you can try and visit "https://localhost:3000/Landing". For the styles you can make a new folder called "/styles" at the root and put the landing.css there

**Review by amanzanero — CHANGES_REQUESTED** [review]
So something with Next js is that everything under "/pages" gets served as a route by next. So I would move all the code from Landing.js and put it in /pages/index.js. Because right you can try and visit "https://localhost:3000/Landing". For the styles you can make a new folder called "/styles" at the root of the repo and put the landing.css there

**Comment by chevrechou** [comment]
ok i changed it

**Comment by amanzanero** [comment]
You have to delete pages/Landing too

**Review by amanzanero — APPROVED** [review]

**Pull request merged**
